title: The Neural Web
author: Ben Weisz
email: your-email@domain.com
description: A collection of interactive AI demos, some of which involving neural networks
twitter_username: 
github_username:  BenWeisz

markdown: kramdown
theme: minima
